const express=require('express');const http=require('http');const path=require('path');const crypto=require('crypto');const bcrypt=require('bcryptjs');const Database=require('better-sqlite3');const session=require('express-session');const {Server}=require('socket.io');
const app=express(),server=http.createServer(app),io=new Server(server);const db=new Database(path.join(__dirname,'typing-battles.db'));db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,elo INTEGER NOT NULL DEFAULT 1000,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS matches(id INTEGER PRIMARY KEY AUTOINCREMENT,mode TEXT NOT NULL,winner_id INTEGER,loser_id INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);`);
app.use(express.json());app.use(express.static(path.join(__dirname,'public')));app.use(session({secret:process.env.SESSION_SECRET||crypto.randomBytes(32).toString('hex'),resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:1000*60*60*24*30}}));
const users=new Map(),queue=[] ,rooms=new Map();const words=['apple','planet','keyboard','velocity','sunlight','mountain','river','window','future','computer','garden','orange','silver','rocket','coffee','forest','typing','battle','thunder','ocean','purple','winter','summer','friend','coding','castle','dragon','music','puzzle','energy'];
function userFromReq(req){return req.session.userId?db.prepare('SELECT id,username,elo FROM users WHERE id=?').get(req.session.userId):null}
app.get('/api/me',(req,res)=>res.json({user:userFromReq(req)}));app.post('/api/signup',(req,res)=>{let {username,password}=req.body||{};username=String(username||'').trim();password=String(password||'');if(!/^[A-Za-z0-9_]{3,20}$/.test(username)||password.length<8)return res.status(400).json({error:'Username must be 3-20 letters/numbers/underscores and password at least 8 characters.'});try{const hash=bcrypt.hashSync(password,12),r=db.prepare('INSERT INTO users(username,password_hash) VALUES(?,?)').run(username,hash);req.session.userId=r.lastInsertRowid;res.json({user:userFromReq(req)})}catch(e){res.status(409).json({error:'Username already exists.'})}});
app.post('/api/login',(req,res)=>{const {username,password}=req.body||{},u=db.prepare('SELECT * FROM users WHERE username=?').get(username);if(!u||!bcrypt.compareSync(String(password||''),u.password_hash))return res.status(401).json({error:'Invalid username or password.'});req.session.userId=u.id;res.json({user:userFromReq(req)})});app.post('/api/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));
function settingsText(s){let out=[];const pool='the quick brown fox jumps over the lazy dog'.split(' ');while(out.join(' ').length<(s.words||30)*6)out.push(pool[Math.floor(Math.random()*pool.length)]);let text=out.slice(0,s.words||30).join(' ');if(s.capitals)text=text.replace(/(^|\s)([a-z])/g,(m,a,b)=>a+b.toUpperCase());if(s.numbers)text=text.split(' ').map((x,i)=>i%7===0?x+Math.floor(Math.random()*90+10):x).join(' ');if(s.punctuation)text=text.replace(/\b(dog|fox|lazy|river|future)\b/g,'$&'+['.','!',',','?'][Math.floor(Math.random()*4)]);return text}
function findOpponent(item){const range=100+Math.floor((Date.now()-item.at)/30000)*50;for(let i=0;i<queue.length;i++){const q=queue[i];if(q.socketId!==item.socketId&&q.mode===item.mode&&Math.abs(q.elo-item.elo)<=range){queue.splice(i,1);return q}}return null}
function socketJoinMatch(socketId,roomId){const s=io.sockets.sockets.get(socketId);if(s)s.join(roomId)}
function startMatch(a,b){const id=crypto.randomUUID(),settings={...a.settings,mode:a.mode},text=settingsText(settings),match={id,a:a.socketId,b:b.socketId,players:{[a.socketId]:{id:a.userId,progress:0,mistakes:0},[b.socketId]:{id:b.userId,progress:0,mistakes:0}},text,settings,started:false};users.set(a.socketId,{...users.get(a.socketId),matchId:id});users.set(b.socketId,{...users.get(b.socketId),matchId:id});socketJoinMatch(a.socketId,id);socketJoinMatch(b.socketId,id);io.to(a.socketId).emit('matchFound',{matchId:id,opponent:{username:b.username,elo:b.elo},text,settings,startsIn:3});io.to(b.socketId).emit('matchFound',{matchId:id,opponent:{username:a.username,elo:a.elo},text,settings,startsIn:3});rooms.set(id,match);setTimeout(()=>{match.started=true;match.startAt=Date.now();io.to(a.socketId).emit('battleStart',{startAt:match.startAt});io.to(b.socketId).emit('battleStart',{startAt:match.startAt})},3200)}
io.on('connection',socket=>{socket.on('identify',()=>{const u=userFromReq(socket.request);if(u){users.set(socket.id,{userId:u.id,username:u.username,elo:u.elo});socket.emit('identified',u)}});socket.on('queueJoin',({mode='casual',settings={}})=>{const u=users.get(socket.id);if(!u)return socket.emit('errorMsg','Reconnect to continue.');if(mode==='ranked'&&!u.userId)return socket.emit('errorMsg','Ranked requires an account.');if(queue.some(x=>x.socketId===socket.id))return;const item={socketId:socket.id,userId:u.userId,username:u.username||'Guest',elo:u.elo||1000,mode,settings,at:Date.now()};const opp=findOpponent(item);if(opp)startMatch(item,opp);else queue.push(item)});socket.on('queueLeave',()=>{const i=queue.findIndex(x=>x.socketId===socket.id);if(i>=0)queue.splice(i,1)});socket.on('progress',({matchId,index,mistakes})=>{const m=rooms.get(matchId),u=users.get(socket.id);if(!m||!u||!m.players[socket.id]||!m.started)return;const p=m.players[socket.id];if(typeof index!=='number'||index<p.progress||index>m.text.length)return;p.progress=index;p.mistakes=Math.max(p.mistakes,Number(mistakes)||0);const limit=m.settings.mistakes;io.to(matchId).emit('opponentProgress',{socketId:socket.id,index,mistakes:p.mistakes});if(limit!=='unlimited'&&p.mistakes>Number(limit))return finish(m,socket.id,false,'mistakes');if(index>=m.text.length)finish(m,socket.id,true,'finish')});socket.on('createRoom',({settings={},privateRoom=false})=>{const code=crypto.randomBytes(3).toString('hex').toUpperCase(),room={code,host:socket.id,private:!!privateRoom,settings,text:settingsText(settings),players:{}};room.players[socket.id]=true;rooms.set('room:'+code,room);socket.join('room:'+code);socket.emit('roomCreated',{code,private:room.private});if(!room.private)io.emit('roomList',publicRooms())});socket.on('roomList',()=>socket.emit('roomList',publicRooms()));socket.on('joinRoom',({code})=>{const room=rooms.get('room:'+String(code||'').toUpperCase());if(!room)return socket.emit('errorMsg','Room not found.');room.players[socket.id]=true;socket.join('room:'+room.code);io.to('room:'+room.code).emit('roomState',{code:room.code,players:Object.keys(room.players).length,settings:room.settings});});socket.on('startRoom',({code})=>{const room=rooms.get('room:'+String(code||'').toUpperCase());if(!room||room.host!==socket.id||Object.keys(room.players).length<2)return;room.text=settingsText(room.settings);room.startAt=Date.now()+3000;io.to('room:'+room.code).emit('roomBattle',{text:room.text,settings:room.settings,startAt:room.startAt})});socket.on('disconnect',()=>{const i=queue.findIndex(x=>x.socketId===socket.id);if(i>=0)queue.splice(i,1);users.delete(socket.id)})});
function publicRooms(){return [...rooms.values()].filter(r=>r.code&&!r.private).map(r=>({code:r.code,players:Object.keys(r.players).length,settings:r.settings}))}

function finish(m,winnerSocket,valid,reason){
  if(m.finished)return;
  m.finished=true;
  const loser=winnerSocket===(m.a)?m.b:m.a;
  const winnerU=users.get(winnerSocket),loserU=users.get(loser);

  if(m.settings.mode==='ranked'&&valid&&winnerU?.userId&&loserU?.userId){
    const k=.03,expected=1/(1+Math.pow(10,(loserU.elo-winnerU.elo)/400));
    const delta=Math.max(10,Math.round(32*(1-expected)));
    db.prepare('UPDATE users SET elo=elo+? WHERE id=?').run(delta,winnerU.userId);
    db.prepare('UPDATE users SET elo=MAX(100,elo-?) WHERE id=?').run(delta,loserU.userId);
    db.prepare('INSERT INTO matches(mode,winner_id,loser_id) VALUES(?,?,?)').run('ranked',winnerU.userId,loserU.userId);
  }

  io.to(m.a).emit('battleEnd',{winner:winnerSocket,reason,valid});
  io.to(m.b).emit('battleEnd',{winner:winnerSocket,reason,valid});
  setTimeout(()=>rooms.delete(m.id),10000);
}

app.use((req,res,next)=>{
  if(req.method!=='GET') return next();
  res.sendFile(path.join(__dirname,'public','index.html'));
});

server.listen(
  process.env.PORT||3000,
  ()=>console.log('Typing Battles running on '+(process.env.PORT||3000))
);